### ISSUE TITLE
Podspec failing linting

### ISSUE THREAD

**Issue by shirakaba** [ammarahm-ed/nativescript-magic-spells#5]
I thought I'd run the Cocoapods linter just in case we've missed anything, and I did happen to find something!

## React-Core

The `React/**/*.{c,h,m,mm,S,cpp}` file path that I copied as-is from the React Native [React-Core.podspec](https://github.com/facebook/react-native/blob/4e70376dc722b6beb7b5b6d6c042b748a9ed14fd/React-Core.podspec#L61) likely needs changing to `lib/**/*.{c,h,m,mm,S,cpp}`. There doesn't seem to be a consequence for now, but it may become relevant if we ever adapt more directories from the React Native source.

```sh
$ cd packages/react-native/platforms/ios
$ pod lib lint React-Core.podspec
 -> React-Core (1.0.0)
    - WARN  | [iOS] license: Unable to find a license file
    - NOTE  | [React-Core/Default] xcodebuild:  note: Using new build system
    - NOTE  | [React-Core/Default] xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [React-Core/Default] xcodebuild:  note: Build preparation complete
    - NOTE  | [React-Core/Default] xcodebuild:  note: Planning
    - NOTE  | [React-Core/Default] xcodebuild:  note: Building targets in dependency order
    - ERROR | [iOS] [React-Core/Default] file patterns: The `source_files` pattern did not match any file.
```

## React

I'm unable to lint this as it doesn't know where to find the `React-Core` spec. Not really sure how to help it! But it's so basic that it's probably fine.

If I do try commenting out the dependencies (as I did to generate this output below), it complains merely about the lack of dependencies, so I think we're okay!

```sh
$ cd packages/react-native/platforms/ios
$ pod lib lint React.podspec
 -> React (1.0.0)
    - ERROR | [iOS] File Patterns: The React (1.0.0) spec is empty (no source files, resources, resource_bundles, preserve paths, vendored_libraries, vendored_frameworks, dependencies, nor subspecs).
    - ERROR | [iOS] unknown: Encountered an unknown error (The `React` pod failed to validate due to 1 error:
    - ERROR | [iOS] File Patterns: The React (1.0.0) spec is empty (no source files, resources, resource_bundles, preserve paths, vendored_libraries, vendored_frameworks, dependencies, nor subspecs).

) during validation.
```

**Comment by ammarahm-ed** [comment]
I think that is acceptable as when running lint on the podspec independently it doesn't know where the React-Core pod is or React pod is. They are all linked through the app level podfile.
