### ISSUE TITLE
RNTestModule getting included twice

### ISSUE THREAD

**Issue by shirakaba** [ammarahm-ed/nativescript-magic-spells#6]
I spotted this in the Xcode console output:

> objc[7758]: Class RNTestModule is implemented in both /Users/jamie/Library/Developer/CoreSimulator/Devices/D070EBAB-5E23-4092-AB2B-4E9F29ADCBEC/data/Containers/Bundle/Application/247CD73D-3C4E-4E14-BDB0-C0128F5529FD/demo.app/Frameworks/react_native_module_test.framework/react_native_module_test (0x10172c810) and /Users/jamie/Library/Developer/CoreSimulator/Devices/D070EBAB-5E23-4092-AB2B-4E9F29ADCBEC/data/Containers/Bundle/Application/247CD73D-3C4E-4E14-BDB0-C0128F5529FD/demo.app/demo (0x100e80d80). One of the two will be used. Which one is undefined.

If you truncate to just the `demo.app` bundle, those paths reduce to:

```
demo.app/Frameworks/react_native_module_test.framework/react_native_module_test
demo.app/demo
```

I think it's almost certainly due to the fact that it's being referenced for compilation twice. Once from `tools/assets/App_Resources/iOS/Podfile` and again from NativeScript CLI's default behaviour of looking in `<package-name>/platforms/ios/src/**/*.m`. So we just need to move these:

```
packages/react-native-module-test/platforms/ios/src/RNTestModule.h
packages/react-native-module-test/platforms/ios/src/RNTestModule.m
```

... to somewhere the NativeScript CLI won't be looking for them, e.g.:

```
packages/react-native-module-test/ios/RNTestModule.h
packages/react-native-module-test/ios/RNTestModule.m
```

... and update `packages/react-native-module-test/react-native-module-test.podspec`'s `source_files` key accordingly.

I'm sure this is on the to-do list already, but just to keep track of it!

**Comment by shirakaba** [comment]
I've addressed this in the commit "fix: stop RNTestModule.m being compiled twice" on my branch `origin/augment-headers` because it might be getting in the way of something else (my CLI build is failing, despite Xcode build succeeding). We can cherry-pick it into the main branch if it's needed sooner for other feature work.

**Comment by ammarahm-ed** [comment]
We probably should not have a platform folder in the react native module since all react native modules are placed in the ios folder at the root. 

Btw I am working on the bridge part on iOS. I hope to finish it soon.
